FROM dleehr/blast
# TODO: make a python image. blast is not necessary
MAINTAINER Dan Leehr <dan.leehr@duke.edu>

ADD extract_go_terms.py /usr/bin/extract_go_terms.py

CMD ["/usr/bin/extract_go_terms.py"]
